name: 'Test'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Install dependencies (ubuntu only)
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make binaryen python3.11 curl

      - name: Install extism-js
        run: |
          curl -O https://raw.githubusercontent.com/extism/js-pdk/main/install.sh
          bash install.sh
          ldd --version

      - name: "Install Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"

      - name: "Cache cargo"
        id: cache-cargo
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          save-always: true
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
  
      - name: "Install moodriver or use the cached version"
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: "cargo install --git https://github.com/Moosync/moodriver"

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Run Tests
        run: |
          mkdir dist
          bun run test -v
