name: 'Test'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Install dependencies (ubuntu only)
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make binaryen python3.11 curl

      - name: Install extism-js
        run: |
          curl -O https://raw.githubusercontent.com/extism/js-pdk/main/install.sh
          bash install.sh
          ldd --version

      - name: Install moodriver
        run: |
          curl -L -o moodriver.zip https://github.com/Moosync/moodriver/releases/download/v1.0.0/moodriver-x86_64-unknown-linux-gnu.zip
          unzip moodriver.zip
          chmod +x moodriver
          sudo mv moodriver /usr/local/bin/

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Run Tests
        run: |
          mkdir dist
          bun run test -v
